[package]
name = "vault-prover-programs"
description = "SP1 zkVM programs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
pegout_test_program_script = { path = "./pegout_test_program_script" }
