[package]
name = "test_program_script"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sp1-sdk = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }